### ISSUE TITLE
problem in project fashion mnist kaggle

### ISSUE THREAD

**Issue by mohamedalswaify** [MohmedAAK/-Advanced-computer-vision-v1#8]
@MohmedAAK 

I have a problem with the first cell and the second cell. Please take a look and help. Thank you

**Comment by MohmedAAK** [comment]
@mohamedgamal1455 ,In first cell : the problem is using something meant for kaggle that access path that only exit in kaggle not colab you can either use the code in kaggle by copy and edit the kernel that you saw code at or just Delete last two lines 
But remember to have data stored in path and use that path in colab 
For example:
data_train = pd.read_csv('../input/fashion-mnist_train.csv') is wrong
Use 
data_train = pd.read_csv('fashion-mnist_train.csv')
But after you upload fashion-mnist_train.csv to colab 
This is data problem and environment problem

To the second cell , the problem is library version 
Use 
from tensorflow.keras.utils import to_categorical
Instead of using keras

**Comment by MohmedAAK** [comment]
BTW 
Use tensorflow.
Before any keras import 
For example 
Import keras
Import keras.layers
Change them to
Import tensorflow.keras
Import tensorflow.keras.layers
To avoid later problems
